### ISSUE TITLE
Control Work # 0

### ISSUE THREAD

**Issue by oleksandrblazhko** [oleksandrblazhko/ai-192-nikova#3]
Правильна відповідь на контрольне запитання дозволить вам отримати додаткові 2 бали 
до балів за виконання лабораторної роботи, якщо ви виявите бажання надати таку відповідь.
Відповідайте на запитання через коментар.

10) Відомо, що GitHub-сервер використовує Token для процедури аутентифікації користувача. 
Але під час створення Token система запропонували вам виконати додаткові налаштування. 
Поясніть, будь ласка, які налаштування та з якому метою було вами виконано?

**Comment by MsNikova** [comment]
Під час створення токена у нас є можливість визначити контроль приватних репозиторіїв, контроль маркерів організацій та команд, що відносяться до репозиторію(Org and Team Membership), контроль публічних ключів користувача, доступ до оновлення User Data(даних користувача).

Завдяки цьому можна розмежити права користування репозиторію, наприклад, лише контроль репозиторію без можливості його видалення, контроль доступу користувачів до цього репозиторії і тп.

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
Оцінка = 2 бали
